<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>f42b0caa-aa2e-4b36-8d42-1849ed63f9de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SidebarContent']/a[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SidebarContent > a:nth-of-type(3) > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SidebarContent >> internal:role=link >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>59860883-f7e7-4c2a-87d1-f920b7e95c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/cats_icon.gif</value>
      <webElementGuid>ac4bec99-f16f-4ebb-a3fe-ced2c9b166cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SidebarContent&quot;)/a[3]/img[1]</value>
      <webElementGuid>5272273b-841e-470f-9d00-35c884c1c0f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SidebarContent']/a[3]/img</value>
      <webElementGuid>dc2a46cc-03c9-4a58-b06a-3c577f16a194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[3]/img</value>
      <webElementGuid>b9ad8dc1-1e70-4e5d-953c-81d4964bba10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/cats_icon.gif']</value>
      <webElementGuid>7c63b81c-47e0-4974-9401-1a543dd7b66f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
