<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>area</name>
   <tag></tag>
   <elementGuidId>98562803-3965-4849-a8bc-902132ec3fae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MainImageContent']/map/area</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>area[alt=&quot;Birds&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Birds&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>area</value>
      <webElementGuid>9e69fe8a-d91e-4b2b-8c5b-b44f83930d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Birds</value>
      <webElementGuid>3938f084-f9e8-43dc-807e-cbc09206b9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>coords</name>
      <type>Main</type>
      <value>72,2,280,250</value>
      <webElementGuid>e2c87600-4b2a-4bd4-9319-c23caefd28af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Catalog.action?viewCategory=&amp;categoryId=BIRDS</value>
      <webElementGuid>d39c244c-f31e-4245-9763-dbb2062aac1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>RECT</value>
      <webElementGuid>61613116-a888-45e7-9096-cf78fb406b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainImageContent&quot;)/map[1]/area[1]</value>
      <webElementGuid>c74567e4-7b91-49dd-a499-5ca11bd00a25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainImageContent']/map/area</value>
      <webElementGuid>0682c12d-a513-44a5-84f7-e1e41a7ff295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//area</value>
      <webElementGuid>e0dcf8ca-7458-4808-b0c1-f1258eafca9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//area[@alt = 'Birds' and @href = 'Catalog.action?viewCategory=&amp;categoryId=BIRDS']</value>
      <webElementGuid>a2a7681a-9801-4e9d-8c13-1a4acb501cdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
